name: Run CI
on: [push, pull_request]

jobs:
  CI:
    # ℹ️ Available GitHub Actions Runner Images 
    #    https://github.com/actions/runner-images
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: bundle install
      - run: pod install --repo-update

      - name: Set Xcode Version 14.2.0 (iOS 16.2)
        run: sudo xcode-select -s /Applications/Xcode_14.2.0.app

      - name: fastlane
        run: set -o pipefail && bundle exec fastlane travis

      - run: bash <(curl -s https://codecov.io/bash) -J 'FlexLayout' -J 'FlexLayoutTests'

      - run: echo "🍏 This job's status is ${{ job.status }}."
