name: Run CI
on: [push, pull_request]

jobs:
  CI:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: bundle install
      - run: pod install --repo-update

      - name: fastlane
        run: set -o pipefail && bundle exec fastlane travis

      - run: bash <(curl -s https://codecov.io/bash) -J 'FlexLayout' -J 'FlexLayoutTests'

      - run: echo "🍏 This job's status is ${{ job.status }}."
